# Generated by Django 3.2.2 on 2021-09-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='iscompleted',
            field=models.BooleanField(default=False),
        ),
    ]
