# Generated by Django 3.2.2 on 2021-09-20 05:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_item_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, to='todo.category'),
            preserve_default=False,
        ),
    ]
